const routes = [{
  path: '/', component: () => import('@/components/airconditioner'), name: 'airconditioner'
}, { path: '/management', component: () => import('@/components/management'), name: 'management'
}, { path: '/managepopup', component: () => import('@/components/managepopup'), name: 'managepopup'
}, { path: '/battery', component: () => import('@/components/battery'), name: 'battery'
}, { path: '/tire', component: () => import('@/components/tire'), name: 'tire'
}, {path: '/water', component: () => import('@/components/water'), name: 'water'
}, { path: '/rightFrontTire', component: () => import('@/components/rightFrontTire'), name: 'rightFrontTire'
}, { path: '/rightRearTire', component: () => import('@/components/rightRearTire'), name: 'rightRearTire'
}, { path: '/leftFrontTire', component: () => import('@/components/leftFrontTire'), name: 'leftFrontTire'
}, { path: '/leftRearTire', component: () => import('@/components/leftRearTire'), name: 'leftRearTire'
}, { path: '/managePopupRF', component: () => import('@/components/managePopupRF'), name: 'managePopupRF'
}, { path: '/managePopupRR', component: () => import('@/components/managePopupRR'), name: 'managePopupRR'
}, { path: '/managePopupLF', component: () => import('@/components/managePopupLF'), name: 'managePopupLF'
}, { path: '/managePopupLR', component: () => import('@/components/managePopupLR'), name: 'managePopupLR'
}, { path: '/cabinAirFilter', component: () => import('@/components/cabinAirFilter'), name: 'cabinAirFilter'
}, { path: '/managePopupCF', component: () => import('@/components/managePopupCF'), name: 'managePopupCF'
}, { path: '/alarmRF', component: () => import('@/components/alarmRF'), name: 'alarmRF'
}, { path: '/alarmCFilter', component: () => import('@/components/alarmCFilter'), name: 'alarmCFilter'
}, { path: '/alarmRF', component: () => import('@/components/alarmRF'), name: 'alarmRF'
}, { path: '/managepopupBattery', component: () => import('@/components/managepopupBattery'), name: 'managepopupBattery'
}, { path: '/managepopupOil', component: () => import('@/components/managepopupOil'), name: 'managepopupOil'
}, { path: '/managePopupWater', component: () => import('@/components/managePopupWater'), name: 'managePopupWater'
}, { path: '/alarmEngineOil', component: () => import('@/components/alarmEngineOil'), name: 'alarmEngineOil'
}, { path: '/alarmBattery', component: () => import('@/components/alarmBattery'), name: 'alarmBattery' } ]

export default routes
